# Generated by Django 5.2.16 on 2026-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=3)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
